version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

  deploy_to_vercel:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel
      - run:
          name: Deploy to Vercel
          command: vercel --prod --token $V_Token

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - summaryComponent
                - questionComponent
                - feature/quizComponent
                - feature/addQuestions
      - deploy_to_vercel:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - summaryComponent
                - questionComponent
                - feature/quizComponent
                - feature/addQuestions
